### ISSUE TITLE
Hello，may i ask you some questions

### ISSUE THREAD

**Issue by wudizuixiaosa** [implus/UM-MAE#2]
Hello, first of all, thank you very much for your excellent works. In addition, I would like to ask whether your downstream task uses maskcnn, which is the part of target detection. Have you considered joining mmselfsup? I think it can let more people know your model. I am also a CV practitioner who is very interested in MAE. I thought before that the images used in the pre training phase are masked, and you are a secondary mask, while the downstream tasks input images that are not masked. Will there be some bias in the parameters. Do you have any better ideas? I'd like to discuss them.

**Comment by implus** [comment]
I believe that ``some bias in the parameters'' would not be a serious problem since SimMIM also applies a lot of (>70% usually) masked patches during pre-traning and SimMIM shows good performance on downstream tasks in its appendix. We are planning to contribute to mmselfsup recently when we are available.  Further, HTC++ is an advanced version of maskrcnn, and we have already proven its effectiveness using HTC++, thus it would definitely work for maskrcnn as well. Thanks for your interest!

**Comment by wudizuixiaosa** [comment]
Oh, it's a great honor for me to reply so quickly. I see from your paper that there is a great improvement in Mae, because Mae can only use unstructured input before, which basically locks vit, although it is great. The subsequent swin and other vit based improvements can only use structured input. Simmim solved this problem, so I thought simmim had greater potential at that time, but your paper gave me more ideas. I hope you can allow me to quote your article in my graduation thesis, because it gave me a lot of help.

**Comment by implus** [comment]
Of course you can. It's my honor to provide insights and ideas for you~

**Comment by austinmw** [comment]
Hi, is there there still any plan to add to MMSelfSup?
